FROM apache/airflow:2.8.0-python3.11

USER airflow
COPY requirements.airflow.txt /tmp/requirements.airflow.txt
RUN pip install --no-cache-dir \
    --constraint https://raw.githubusercontent.com/apache/airflow/constraints-2.8.0/constraints-3.11.txt \
    -r /tmp/requirements.airflow.txt